### ISSUE TITLE
Is site down?

### ISSUE THREAD

**Issue by Dihgg** [danielgtaylor/bibviz#8]
is http://bibviz.com down?

**Comment by Truffula** [comment]
Looks like the domain might have lapsed...?

**Comment by jgrose** [comment]
Registrar Expiration Date: 2018-08-15

So unless it's renewed soon it will lapse. =/

**Comment by Dihgg** [comment]
Looks like it is up again

**Comment by christopher-noq** [comment]
Phew! Thank the FSM! 😆

**Comment by that1guyovathere** [comment]
It's down again. Anyone have any idea what's going on? This was an invaluable resource. I'd pay for the hosting to get it back online...

**Comment by rodrigofaustino** [comment]
I intend to launch on my own with Portuguese translation, but in the tests it brings me a problem: The "path" argument must be of type string. Received undefined
